// INT OS Constants and Configuration

export const APPS = [
  {
    id: 1,
    name: 'InsightHub',
    path: '/insights',
    icon: 'BarChart3',
    description: 'Real-time analytics and business intelligence',
    color: '#00E5FF',
  },
  {
    id: 2,
    name: 'AcademyPortal',
    path: '/academy',
    icon: 'GraduationCap',
    description: 'Learning management and certification tracking',
    color: '#6B9FFF',
  },
  {
    id: 3,
    name: 'PulseBoard',
    path: '/pulse',
    icon: 'Activity',
    description: 'Team health and engagement metrics',
    color: '#48E5AC',
  },
  {
    id: 4,
    name: 'ResolveDesk',
    path: '/resolve',
    icon: 'Ticket',
    description: 'AI-powered support ticket management',
    color: '#FF7A50',
  },
  {
    id: 5,
    name: 'StrategyBoard',
    path: '/strategy',
    icon: 'Target',
    description: 'OKRs, goals, and strategic planning',
    color: '#B794F6',
  },
  {
    id: 6,
    name: 'FeedbackLoop',
    path: '/feedback',
    icon: 'MessageSquare',
    description: 'Customer feedback and sentiment analysis',
    color: '#FCD34D',
  },
  {
    id: 7,
    name: 'ConnectDesk',
    path: '/connect',
    icon: 'Users',
    description: 'CRM and contact management hub',
    color: '#00E5FF',
  },
  {
    id: 8,
    name: 'SyncBotPanel',
    path: '/syncbot',
    icon: 'Bot',
    description: 'Automation orchestration and bot management',
    color: '#CBD5E0',
  },
  {
    id: 9,
    name: 'PulseChat',
    path: '/chat',
    icon: 'MessagesSquare',
    description: 'Team communication and collaboration',
    color: '#6B9FFF',
  },
  {
    id: 10,
    name: 'CommandView',
    path: '/command',
    icon: 'Terminal',
    description: 'System administration and operations',
    color: '#E2E8F0',
  },
  {
    id: 11,
    name: 'AssuranceBoard',
    path: '/assurance',
    icon: 'Shield',
    description: 'Compliance, security, and audit trails',
    color: '#34D399',
  },
  {
    id: 12,
    name: 'BrainDock',
    path: '/brain',
    icon: 'Brain',
    description: 'AI knowledge base and documentation',
    color: '#B794F6',
  },
  {
    id: 13,
    name: 'FlowForge',
    path: '/flow',
    icon: 'GitBranch',
    description: 'Workflow automation and process builder',
    color: '#FF9470',
  },
  {
    id: 14,
    name: 'SentimentScope',
    path: '/sentiment',
    icon: 'Smile',
    description: 'Emotion detection and sentiment tracking',
    color: '#FCD34D',
  },
  {
    id: 15,
    name: 'AlertOps',
    path: '/alerts',
    icon: 'Bell',
    description: 'Incident management and on-call routing',
    color: '#F87171',
  },
  {
    id: 16,
    name: 'TriageLens',
    path: '/triage',
    icon: 'Layers',
    description: 'Priority queue and ticket routing AI',
    color: '#48E5AC',
  },
  {
    id: 17,
    name: 'PartnerHub',
    path: '/partners',
    icon: 'Handshake',
    description: 'Partner portal and collaboration workspace',
    color: '#6B9FFF',
  },
  {
    id: 18,
    name: 'INT_Studio',
    path: '/studio',
    icon: 'Sparkles',
    description: 'No-code app builder and customization',
    color: '#FF7A50',
  },
] as const;

export const ROLES = {
  VIEWER: 'viewer',
  AGENT: 'agent',
  MANAGER: 'manager',
  ADMIN: 'admin',
} as const;

export const LANGUAGES = [
  { code: 'en', label: 'English', direction: 'ltr' },
  { code: 'es', label: 'Español', direction: 'ltr' },
  { code: 'fr', label: 'Français', direction: 'ltr' },
  { code: 'ar', label: 'العربية', direction: 'rtl' },
] as const;

export const KEYBOARD_SHORTCUTS = {
  COMMAND_PALETTE: ['cmd+k', 'ctrl+k'],
  SEARCH: ['cmd+/', 'ctrl+/'],
  NAVIGATION: ['cmd+1...9', 'ctrl+1...9'],
  TOGGLE_SIDEBAR: ['cmd+b', 'ctrl+b'],
  TOGGLE_ASSISTANT: ['cmd+i', 'ctrl+i'],
} as const;